apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-main
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-prod
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - opmdsogheactionsrunners.usgovvirginia.cloudapp.usgovcloudapi.net
      secretName: tlsingress
  rules:
  - host: opmdsogheactionsrunners.usgovvirginia.cloudapp.usgovcloudapi.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-app
            port:
              number: 80
      - path: /default/runners-scaler
        pathType: Prefix
        backend:
          service:
            name: default-github-webhook-server
            port:
              number: 80
